### ISSUE TITLE
一些体验少少问题

### ISSUE THREAD

**Issue by LIANGWEIBIAO** [jeneser/douban#11]
上拉加载更多数据，然后点进某一个详情页，返回的时候没有记录上一页的位置而是返回顶部这个要怎么样解决比较好？

**Comment by jeneser** [comment]
Hello, thanks for opening an issue with me.

>We can use scrollBehavior of vue-router

We may want to scroll to top when navigating to a new route, or preserve the scrolling position of history entries just like real page reload does. `vue-router` allows you to achieve these and even better.

*BUT:scrollBehavior only works in HTML5 history mode. The demo deploy on github pages , it does not support history mode.*

Please see the following link: [scrollBehavior](https://router.vuejs.org/en/advanced/scroll-behavior.html)
