### ISSUE TITLE
header-bar组件是如何组合的？

### ISSUE THREAD

**Issue by jfliapp** [jeneser/douban#17]
你好！！ 我最近在学vue 看了你的写的项目。写的很好！ 但是有点看不懂的地方就是那个 头部的
 header-bar  你是怎么插进去的  我看不懂？希望 能教一下我

**Comment by jeneser** [comment]
你好！感谢您提交issue给我。
`header-bar`本身是作为一个一次性组件在这里出现的，在`src/views/PagesView.vue`中对其进行了组合。这里涉及了路由，具名的路由出口以及子路由等，通过这种组合，我们可以创建多个平行的视图，使得固定的头部导航与应用的其他视图共存，以满足我们的设计需求。
在这篇文章中我进行了简单的分析，你可以参考一下: [杂篇 - Vue豆瓣系列文章
](http://www.jianshu.com/p/3e4d06b9e0fd)
Thanks.

**Comment by jfliapp** [comment]
谢谢 指点 我懂了

**Comment by jeneser** [comment]
Right!
我将关闭本issue。感谢你的关注！
