### ISSUE TITLE
图片全挂了

### ISSUE THREAD

**Issue by imgwho** [jeneser/douban#20]
![TIM截图20171105123258.png](https://i.loli.net/2017/11/05/59fe9484d1ae9.png)
在 index.html里加上 
```
<meta name="referrer" content="never">
```
即可 [参考](https://imququ.com/post/referrer-policy.html)

**Comment by jeneser** [comment]
@imgwho 感谢您提交Issue给我。
为了方便并兼顾未知BUG，按照您的提示选择使用<meta>标签指定 Referrer 策略来修复该问题。[PR #21](https://github.com/jeneser/douban/pull/21)

Thanks.
