### ISSUE TITLE
豆瓣api挂了么？

### ISSUE THREAD

**Issue by lydia1883** [jeneser/douban#22]
![v a 0j2_e _au8ypmjs0u](https://user-images.githubusercontent.com/13453799/33258180-9d746e52-d393-11e7-8845-54ed08fc2a5c.png)
这个能做容错么？

**Comment by jeneser** [comment]
能详细描述一下吗？

**Comment by lydia1883** [comment]
其实就是希望优化一下用户体验，在豆瓣接口挂了的时候代码不会报错

**Comment by jeneser** [comment]
好的，感谢你的建议。优化用户体验将会在后续进行。如果对此你有解决方案，我们非常欢迎您提交PR来帮助改善此问题。
Thanks.

**Comment by lydia1883** [comment]
项目很好，目前我也正在学习你的写法，也同时在学习vue, 有建议我会随时提起

**Comment by 1008611** [comment]
使用最新版本的 "superagent-jsonp"0.2.1，在network中能获取到数据，但是在控制台中会报“superagentCallback153xxxxxxxxx”错误。
