### ISSUE TITLE
为什么App.vue 要写三个<router-view>, 不明白这里的写法

### ISSUE THREAD

**Issue by zhouxin1233** [jeneser/douban#24]
如题

**Comment by bailongctui** [comment]
[](https://www.jianshu.com/p/3e4d06b9e0fd)
作者这篇文章应该能帮到你理解下。

**Comment by bailongctui** [comment]
[](https://www.jianshu.com/p/3e4d06b9e0fd)

**Comment by AcaciusShun** [comment]
https://www.jianshu.com/p/3e4d06b9e0fd
作者这篇文章应该能帮到你~

**Comment by jeneser** [comment]
是的，可以参考该文章：https://www.jianshu.com/p/3e4d06b9e0fd
Thanks.
