### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by dawang0123** [jeneser/douban#28]
➜  douban npm run dev
npm ERR! missing script: dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wangqian/.npm/_logs/2018-04-20T10_12_21_542Z-debug.log
![image](https://user-images.githubusercontent.com/11239282/39046030-4b7fdcda-44c7-11e8-8a57-2d6f3b837390.png)
全局更新npm后，版本升级到5.8，仍然不管用，是什么原因导致的呢

**Comment by 8886666** [comment]
请问这个问题你解决了吗

**Comment by Gringe920** [comment]
是不是因为本地开了两个vue项目，把端口号8080改下试试

**Comment by dawang0123** [comment]
改过端口号不起效……

**Comment by Gringe920** [comment]
package.json 里面script参数 有dev吗

**Comment by jeneser** [comment]
经测试并无问题，请耐心检查开发环境是否配置正确，如有疑问请新建issue并提供更多详细信息。

我将关闭此issue，thanks.
