### ISSUE TITLE
Deploying to pages yields blank page

### ISSUE THREAD

**Issue by jeneser** [jeneser/douban#6]
Hi,
I created the project with vue-cli. 'npm run dev' has worked flawlessly. Wanted to test a version of the app on my hosting server and my github pages.But the pages is blank.Before this,I have modified `config->index.js->assetsPublicPath: './'`,There no any error in the console.please help me ~~thanks~~

**Comment by jeneser** [comment]
hi,boy
I guess,you may Using the history mode in your router,please remove it,everything is ok!
I'm looking for the answer,
WHY:Using history mode renders blank, but no errors.

**Comment by UNDERCOVERj** [comment]
`error:cant find python executable...`
请问什么是node-gyp呢，用来干什么的?
api会设计跨域吗？

**Comment by UNDERCOVERj** [comment]
[vue-router] missing param for named route "SubjectView": Expected "id" to be defined

**Comment by jeneser** [comment]
@UNDERCOVERj 
Hello, thanks for opening an issue with me.
Would you mind if I move your issue to a new place?
Please look here: https://github.com/jeneser/douban/issues/7

**Comment by jeneser** [comment]
Hi,
You can vist the doc to learn more.
[HTML5 History Mode](https://router.vuejs.org/en/essentials/history-mode.html)
